{
 "title": "OpenTelemetry APM",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{service_name!=\"nginx\"},service_name)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "traces_span_metrics_calls_total"
    }
   },
   { "name": "rate_interval", "query": "1m, 3m, 5m, 10m" }
  ]
 },
 "panels": [
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PR50 Latency",
   "type": "timeseries",
   "description": "PR50 latency",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"nginx\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR95 Latency",
   "type": "timeseries",
   "description": "PR95 latency",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"nginx\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PR99 Latency",
   "type": "timeseries",
   "description": "PR99 latency",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"nginx\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "max Latency",
   "type": "timeseries",
   "description": "max latency",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"nginx\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"nginx\", span_kind=\"SPAN_KIND_SERVER\"}[3m]))  by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Rate for ${app} by route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"nginx\"}[$rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency for ${app}, PR50",
   "type": "timeseries",
   "description": "PR50  latency",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Latency for ${app}, PR95",
   "type": "timeseries",
   "description": "PR95 latency",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency for ${app}, PR99",
   "type": "timeseries",
   "description": "PR99  latency",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{spane_name}}"
    }
   ]
  },
  {
   "title": "Latency for ${app}, max",
   "type": "timeseries",
   "description": "max  latency",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}[$rate_interval])) by (le, span_name))",
     "legendFormat": "{{spane_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(traces_span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", http_status_code!=\"\", span_name=~\"$route\"} / traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", http_status_code!=\"\", span_name=~\"$route\"})",
     "legendFormat": "[{{http_status_code}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}[3m]))"
    }
   ]
  },
  {
   "title": "Error Rate for ${app} by route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 26 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"${app}\", span_name=~\"${route}\"}[$rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Loading Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_sum{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"}) by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", http_status_code=~\"5.*|\", span_name=~\"$route\"})/sum(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$app\", span_name=~\"$route\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$app\", span_kind=\"SPAN_KIND_SERVER\", span_name=~\"$route\"}[$rate_interval]))  by(span_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}