{
 "title": "Otel - kubeletstats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deploy_name",
    "label": "Deploy Name",
    "query": {
     "query": "label_values(k8s_deployment_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU Usage",
   "type": "gauge",
   "description": "This metric measures the average CPU utilization across all the containers in a given Pod. It represents the overall CPU utilization of the Pod, including all the containers running within it.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_cpu_utilization_ratio{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Pod {{k8s_pod_name}} CPU Usage"
    }
   ]
  },
  {
   "title": "Pod Used RAM",
   "type": "piechart",
   "description": "This metric measures the memory utilization across all the containers in a given Pod. It represents the overall memory utilization of the Pod, including all the containers running within it.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_pod_memory_available_bytes{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Available RAM {{k8s_deployment_name}}"
    },
    {
     "expr": "k8s_pod_memory_usage_bytes{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Used RAM {{k8s_deployment_name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_container_restarts{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k8s_container_cpu_limit{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Limit for {{k8s_container_name}} from {{k8s_deployment_name}}"
    },
    {
     "expr": "k8s_container_cpu_request{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Request for {{k8s_container_name}} from {{k8s_deployment_name}}"
    },
    {
     "expr": "rate(container_cpu_time_seconds_total{k8s_deployment_name=\"$deploy_name\"}[1m])",
     "legendFormat": "Usage for {{k8s_container_name}} from {{k8s_deployment_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Container {{k8s_container_name}} used CPU"
    }
   ]
  },
  { "title": "Resources - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage (pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_pod_memory_usage_bytes{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Pod {{k8s_pod_name}} Used RAM"
    },
    {
     "expr": "k8s_pod_memory_available_bytes{k8s_deployment_name=\"$deploy_name\"}",
     "legendFormat": "Pod {{k8s_pod_name}} Available RAM"
    }
   ]
  }
 ]
}