# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Loki
    orgId: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
#prune: true

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: Prometheus
    # <string, required> Sets the data source type.
    type: prometheus
    typeName: Prometheus
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: prometheus
    # <string> Sets the data source's URL, including the
    # port.
    url: http://prometheus:9090
    # <string> Sets the database user, if necessary.
    user: ''
    # <string> Sets the database name, if necessary.
    password: ''
    database: ''
    # <bool> Enables basic authorization.
    basicAuth: false
    # <bool> Toggles whether the data source is pre-selected
    # for new panels. You can set only one default
    # data source per organization.
    isDefault: true
     # <map> Fields to convert to JSON and store in jsonData.
    jsonData:
      httpMethod: POST
    readOnly: false
    # <bool> Allows users to edit data sources from the
    # Grafana UI
    editable: true
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
    readOnly: false
    editable: true