apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-mongodb
  namespace: "workspace-ns"
  labels:
    app.kubernetes.io/instance: workspace
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: workspace
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: workspace
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/component: mongodb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: workspace
                    app.kubernetes.io/name: mongodb
                    app.kubernetes.io/component: mongodb
                topologyKey: kubernetes.io/hostname
              weight: 1

      containers:
        - name: mongodb
          image: mongo:5.0.25
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
#            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: mongodb
              containerPort: 27017
          resources:
            limits:
              cpu: 750m
              ephemeral-storage: 2Gi
              memory: 768Mi
            requests:
              cpu: 500m
              ephemeral-storage: 50Mi
              memory: 512Mi
          volumeMounts:
            - name: db-data
              mountPath: /data/db
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: workspace-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: "workspace-ns"
  labels:
    app.kubernetes.io/instance: workspace
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: "mongodb"
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/instance: workspace
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-mongodb
  namespace: "workspace-ns"
  labels:
    app.kubernetes.io/instance: workspace
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

