#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ASSETS_USER WITH PASSWORD '$ASSETS_PASSWORD';
    CREATE DATABASE $ASSETS_DB OWNER $ASSETS_USER;

    CREATE USER $AUTHENTICATION_USER WITH PASSWORD '$AUTHENTICATION_PASSWORD';
    CREATE DATABASE $AUTHENTICATION_DB OWNER $AUTHENTICATION_USER;
EOSQL
